config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  resources :events
  resources :attendances, only: [:new, :create, :destroy]

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances

  validates :creator_id, :name, :date, :location, :description, presence: true
  validates :date, comparison: { greater_than: Time.current }

  scope :past, -> { where("date < ?", Time.current) }
  scope :upcoming, -> { where("date >= ?", Time.current) }

  def formatted_date
    date.strftime("%d/%m/%y at %H:%M" )
  end

  def created_by?(user)
    creator == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

  validates :username, presence: true

  scope :attending, ->(event) { joins(:attendances).where("attended_event_id = ?", event.id) }

  def attending?(event)
    attended_events.include?(event)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  self.responder = ApplicationResponder
  respond_to :html

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def new
    event = Event.find(params[:event_id])
    @attendances = User.ids.each { |user_id| event.attendances.build(attendee_id: user_id) }
  end

  def create
    @attendance = Attendance.create(attendance_params)
    flash[:sucess] = "You are going to this event!"

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @attendance = Attendance.find_by(attendance_params)

    if @attendance
      @attendance.destroy
      flash[:sucess] = "You are no longer going to this event"
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = "You are not set to attend this event"
    end
  end

  private
    def attendance_params
      params.require(:attendance).permit(:attendee_id, :attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_ownership, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
      flash[:success] = "Your Event was edited successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_path(current_user.id)
    flash[:success] = "Your Event was deleted successfully"
  end

  private
    def event_params
      params.require(:event).permit(:creator_id, :name, :date, :location, :description)
    end

    def check_ownership
      @event = Event.find(params[:id])

      unless @event.created_by?(current_user)
        redirect_back(fallback_location: root_path)
        flash[:error] = "You are not allowed to do that"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/new.html.erb
<%# collection_check_boxes(:attendance, :attendee_id, User.all, :id, :username)%>
<%= turbo_frame_tag "manage-attendances" do %>
    <%= form_with model: @event, url: attendances_path do |f| %>
        <%= f.collection_check_boxes(:user_id, User.all, :id, :username) %>
        <%= f.submit "Invite" %>
    <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :date %>
    <%= f.datetime_field :date %>

    <%= f.label :description %>
    <%= f.text_area :description %>    

    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event%>

app/views/events/index.html.erb
<h1>All Events</h1>

<%= render "shared/events_list", type: "future", events: @events.upcoming %>
<%= render "shared/events_list", type: "past", events: @events.past %>




<%= link_to "Add new Event", new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :date %>
    <%= f.datetime_field :date %>

    <%= f.label :description %>
    <%= f.text_area :description %>    

    <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name.capitalize %></h1>

<ul>
    <li><strong>By: </strong><%= @event.creator.username %></li>
    <li><strong>Date: </strong><%= @event.formatted_date %></li>
    <li><strong>Location:</strong><%= @event.location %></li>
    <li><strong>Description: </strong><br>
        <%= @event.description %></li>
</ul>

<p>
    <%= link_to "Edit", edit_event_path(@event.id) %>
    or
    <%= link_to "Delete", event_path(@event.id), data: {
                                                         turbo_method: :delete,
                                                         turbo_confirm: "Are you sure?"} %>

</p>

<h2>Participants</h2>

<ul>
    <% @event.attendees.each do |attendee| %>
        <li><%= attendee.username %></li>
    <% end %>
</ul>


<% if @event.created_by?(current_user) %>
    <%= turbo_frame_tag "manage-attendances" do %>
        <%= link_to "Manage Attendances", new_attendance_path(event_id: @event.id)%>
    <% end %>
<% end %>

<% if 1 == 2 #user_signed_in? %>
    <% attendance_params =
        {attendance: { attendee_id: current_user.id, attended_event_id: @event.id } } %>

    <%= button_to "Attend", attendances_path, params: attendance_params %>

    <% current_attendance = current_user.attendances.find_by(attended_event_id: @event.id) %>

    <% if current_user.attending?(@event) %>
        <%= button_to "Unattend", attendance_path(current_attendance), 
            method: :delete,
            params: attendance_params,
            data: { turbo_confirm: "Are you sure?" } %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <h1>
          <%= link_to "Private Events", root_path %>
      </h1>

      <div>
        <% if user_signed_in? %>
          Logged in as <%= link_to current_user.username, user_path(current_user.id) %>,
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete,
                                                                    turbo_confirm: "Are you sure?"
                                                                  } %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path%> or <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
    </nav>

    <% if flash.any? %>
      <% flash.each do |type, message| %>
        <p><%= message %></p>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_events_list.html.erb
<h2><%= type.capitalize %> Events</h2>

<%if events.empty? %>
    <p>There are no <%= type %> events</p>
<% else %>
    <ul>
        <% events.each do |event| %>
            <li><%= link_to event.name.capitalize, event_path(event.id) %></li> 
        <% end %>
    </ul>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %> Events</h1>

<%= render "shared/events_list", type: "created", events: @user.created_events %>

<%= render "shared/events_list", type: "upcoming", events: @user.attended_events.upcoming %>

<%= render "shared/events_list", type: "past", events: @user.attended_events.past %>
 